version: "3"
services:
  lavande-mariadb:
    image: mariadb:10.9
    container_name: lavande-mariadb
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
      - lavande_database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=lavender
      - MYSQL_PASSWORD=cihuy
      - MYSQL_ROOT_PASSWORD=rootcihuy
      - MYSQL_DATABASE=lavandeapp
    restart: unless-stopped

volumes:
  lavande_database:
    driver: local
